trigger: none
pool:
  vmImage: ubuntu-20.04

resources:
  repositories:
    - repository: azure-aks-workshop
      type: github
      name: anupamphoghat-contino/azure-aks-workshop
#      endpoint: svc-dtm-cicd
      ref: refs/heads/main

  containers:
    # CI Container, used for tests etc.  Debian is used here as Bash is required
    - container: node
      image: node:16-bullseye
    # Python container for manipulating IaC files
    - container: python
      image: python:3-bullseye


variables:
  imageName: 'continotest.jfrog.io/artifactory-docker-prod-local/test-image'
  artifactoryServiceConnection : 'jfrog'
  targetRepo : 'artifactory-docker-prod-local'
  imageTag : '$(Build.BuildNumber)'


stages:
- stage: BuildPush
  displayName: Build & Push
  jobs:
  - job: Build
    displayName: Build 
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/workshop-app/Dockerfile'
        tags: |
          $(tag)
    - task: ArtifactoryDocker@1
      displayName: "Docker push"
      inputs:
        command: 'push'
        artifactoryService: '$(artifactoryServiceConnection)'
        targetRepo: '$(targetRepo)'
        imageName: '$(imageName):$(imageTag)'


