trigger:
  - master

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: azure-aks-workshop
      type: github
      name: anupamphoghat-contino/azure-aks-workshop
      endpoint: anupamphoghat-contino
      ref: refs/heads/master

variables:
  imageName: 'continotest.jfrog.io/artifactory-docker-prod-local/test-image'
  artifactoryServiceConnection : 'jfrog'
  targetRepo : 'artifactory/artifactory-docker-prod-local/'
  imageTag : '$(Build.BuildNumber)'
  imageRepo: 'artifactory-docker-prod-local/test-image'

steps:
  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: build
      dockerfile: '$(Build.SourcesDirectory)/workshop-app/Dockerfile'
      repository: $(imageName)
      tags: $(imageTag)

  - task: ArtifactoryDocker@1
    displayName: "Docker push"
    inputs:
      command: 'push'
      artifactoryService: '$(artifactoryServiceConnection)'
      targetRepo: '$(targetRepo)'
      imageName: '$(imageName):$(imageTag)'
