trigger:
  - master

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: azure-aks-workshop
      type: github
      name: anupamphoghat-contino/azure-aks-workshop
      endpoint: anupamphoghat-contino
      ref: refs/heads/master

variables:
  imageName: 'continotest.jfrog.io/artifactory-docker-prod-local/test-image'
  artifactoryServiceConnection : 'azuredevopsjfrog'
#  dockerRegistryServiceConnection: 'dockerregistry'
  devRepo : 'artifactory-docker-prod-local'
  prodRepo : 'default-docker-local'
  sourceRepo: 'test-image'
  imageTag : '$(Build.BuildNumber)'

steps:
  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: build
#      containerRegistry: '$(dockerRegistryServiceConnection)'
      dockerfile: './Dockerfile'
      repository: '$(imageName)'
      tags: $(imageTag)

  - task: ArtifactoryDocker@1
    displayName: "Docker push"
    inputs:
      command: 'push'
      artifactoryService: '$(artifactoryServiceConnection)'
      targetRepo: '$(devRepo)'
      imageName: '$(imageName):$(imageTag)'
#      collectBuildInfo: false


  - task: ArtifactoryDocker@1
    displayName: "Docker push"
    inputs:
      command: 'push'
      artifactoryService: '$(artifactoryServiceConnection)'
      targetRepo: '$(prodRepo)'
      sourceRepo: '$(devRepo)'
      imageName: '$(imageName):$(imageTag)'