trigger:
  - master

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: azure-aks-workshop
      type: github
      name: anupamphoghat-contino/azure-aks-workshop
      endpoint: anupamphoghat-contino
      ref: refs/heads/master

variables:
  artifactoryDomain: continotest.jfrog.io
  imageName: 'continotest.jfrog.io/artifactory-docker-prod-local/test-image'
  artifactoryServiceConnection : 'jfrog'
  dockerRegistryServiceConnection: 'dockerhub'
  targetRepo : 'artifactory-docker-prod-local'
#  sourceRepo: 'test-image'
  sourceRepo: 'artifactory-docker-prod-local/test-image'
  imageTag : '$(Build.BuildNumber)'

steps:
  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: build
#      containerRegistry: '$(dockerRegistryServiceConnection)'
      dockerfile: '**/Dockerfile'
      repository: $(artifactoryDomain)/$(sourceRepo)
      tags: $(imageTag)

  - task: ArtifactoryDocker@1
    displayName: "Docker push"
    inputs:
      command: 'push'
      artifactoryService: '$(artifactoryServiceConnection)'
      targetRepo: '$(targetRepo)'
      imageName: '$(artifactoryDomain)/$(sourceRepo):$(imageTag)'
